
module.exports = {
  ADD_ARTICLE: 'ADD_ARTICLE',
  ADD_ARTICLE_SUCCESS: 'ADD_ARTICLE_SUCCESS',
  ADD_ARTICLE_ERROR: 'ADD_ARTICLE_ERROR',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
  UPDATE_ARTICLE_ERROR: 'UPDATE_ARTICLE_ERROR'
};
