
module.exports = {
  ADD_ASSESMENT: 'ADD_ASSESMENT',
  ADD_ASSESMENT_SUCCESS: 'ADD_ASSESMENT_SUCCESS',
  ADD_ASSESMENT_ERROR: 'ADD_ASSESMENT_ERROR',
  UPDATE_ASSESMENT: 'UPDATE_ASSESMENT',
  UPDATE_ASSESMENT_SUCCESS: 'UPDATE_ASSESMENT_SUCCESS',
  UPDATE_ASSESMENT_ERROR: 'UPDATE_ASSESMENT_ERROR',
  GET_ASSESSMENT: 'GET_ASSESSMENT',
  GET_ASSESSMENT_SUCCESS: 'GET_ASSESSMENT_SUCCESS',
  GET_ASSESSMENT_ERROR: 'GET_ASSESSMENT_ERROR',
  SUBMIT_ASSESSMENT: 'SUBMIT_ASSESSMENT',
  SUBMIT_ASSESSMENT_SUCCESS: 'SUBMIT_ASSESSMENT_SUCCESS',
  SUBMIT_ASSESSMENT_ERROR: 'SUBMIT_ASSESSMENT_ERROR',
  GET_ASSESSMENT_RESULT: 'GET_ASSESSMENT_RESULT',
  GET_ASSESSMENT_RESULT_SUCCESS: 'GET_ASSESSMENT_RESULT_SUCCESS',
  GET_ASSESSMENT_RESULT_ERROR: 'GET_ASSESSMENT_RESULT_ERROR'
};
