
module.exports = {
  ADD_BOOK: 'ADD_BOOK',
  ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
  ADD_BOOK_ERROR: 'ADD_BOOK_ERROR',
  UPDATE_BOOK: 'UPDATE_BOOK',
  UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
  UPDATE_BOOK_ERROR: 'UPDATE_BOOK_ERROR'
};
