module.exports = {
  CREATE_PASS_PHRASE: 'CREATE_PASS_PHRASE',
  CREATE_PASS_PHRASE_SUCCESS: 'CREATE_PASS_PHRASE_SUCCESS',
  CREATE_PASS_PHRASE_ERROR: 'CREATE_PASS_PHRASE_ERROR',
  GET_CERTIFICATE: 'GET_CERTIFICATE',
  GET_CERTIFICATE_SUCCESS: 'GET_CERTIFICATE_SUCCESS',
  GET_CERTIFICATE_ERROR: 'GET_CERTIFICATE_ERROR',
  GET_DOWNLOAD_URL: 'GET_DOWNLOAD_URL',
  GET_DOWNLOAD_URL_SUCCESS: 'GET_DOWNLOAD_URL_SUCCESS',
  GET_DOWNLOAD_URL_ERROR: 'GET_DOWNLOAD_URL_ERROR',
  UPLOAD_CERTIFICATE: 'UPLOAD_CERTIFICATE',
  UPLOAD_CERTIFICATE_SUCCESS: 'UPLOAD_CERTIFICATE_SUCCESS',
  UPLOAD_CERTIFICATE_ERROR: 'UPLOAD_CERTIFICATE_ERROR'
};
