module.exports = {
  FETCH_COURSE_DETAILS: 'FETCH_COURSE_DETAILS',
  FETCH_COURSE_DETAILS_SUCCESS: 'FETCH_COURSE_DETAILS_SUCCESS',
  FETCH_COURSE_DETAILS_ERROR: 'FETCH_COURSE_DETAILS_ERROR',
  CLEAR_COURSE_DETAILS: 'CLEAR_COURSE_DETAILS',
  SEARCH_COURSE: 'SEARCH_COURSE',
  SEARCH_COURSE_SUCCESS: 'SEARCH_COURSE_SUCCESS',
  SEARCH_COURSE_ERROR: 'SEARCH_COURSE_ERROR',
  GET_SEARCHED_COURSE: 'GET_SEARCHED_COURSE',
  GET_SEARCHED_COURSE_SUCCESS: 'GET_SEARCHED_COURSE_SUCCESS',
  GET_SEARCHED_COURSE_ERROR: 'GET_SEARCHED_COURSE_ERROR',
  GET_EXPERT_SEARCHED_COURSE: 'GET_EXPERT_SEARCHED_COURSE',
  GET_EXPERT_SEARCHED_COURSE_SUCCESS: 'GET_EXPERT_SEARCHED_COURSE_SUCCESS',
  GET_EXPERT_SEARCHED_COURSE_ERROR: 'GET_EXPERT_SEARCHED_COURSE_ERROR',
  UPDATE_MICROLEARNING: 'UPDATE_MICROLEARNING',
  UPDATE_MICROLEARNING_SUCCESS: 'UPDATE_MICROLEARNING_SUCCESS',
  UPDATE_MICROLEARNING_ERROR: 'UPDATE_MICROLEARNING_ERROR'
};
