
module.exports = {
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  ADD_DOCUMENT_SUCCESS: 'ADD_DOCUMENT_SUCCESS',
  ADD_DOCUMENT_ERROR: 'ADD_DOCUMENT_ERROR',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  UPDATE_DOCUMENT_SUCCESS: 'UPDATE_DOCUMENT_SUCCESS',
  UPDATE_DOCUMENT_ERROR: 'UPDATE_DOCUMENT_ERROR'
};
