module.exports = {
  GET_DAILY_GOALS: 'GET_DAILY_GOALS',
  GET_DAILY_GOALS_SUCCESS: 'GET_DAILY_GOALS_SUCCESS',
  GET_DAILY_GOALS_ERROR: 'GET_DAILY_GOALS_ERROR',
  UPDATE_DAILY_GOAL: 'UPDATE_DAILY_GOAL',
  UPDATE_DAILY_GOAL_SUCCESS: 'UPDATE_DAILY_GOAL_SUCCESS',
  UPDATE_DAILY_GOAL_ERROR: 'UPDATE_DAILY_GOAL_ERROR'
};
