module.exports = {
  ADD_ONLINE_COURSE: 'ADD_ONLINE_COURSE',
  ADD_ONLINE_COURSE_SUCCESS: 'ADD_ONLINE_COURSE_SUCCESS',
  ADD_ONLINE_COURSE_ERROR: 'ADD_ONLINE_COURSE_ERROR',
  UPDATE_ONLINE_COURSE: 'UPDATE_ONLINE_COURSE',
  UPDATE_ONLINE_COURSE_SUCCESS: 'UPDATE_ONLINE_COURSE_SUCCESS',
  UPDATE_ONLINE_COURSE_ERROR: 'UPDATE_ONLINE_COURSE_ERROR',
  CLEAR_ONLINE_COURSE_DETAILS: 'CLEAR_ONLINE_COURSE_DETAILS'
};
