module.exports = {
  FETCH_ALL_RECENT_HAPPENINGS: 'FETCH_ALL_RECENT_HAPPENINGS',
  FETCH_ALL_RECENT_HAPPENINGS_SUCCESS: 'FETCH_ALL_RECENT_HAPPENINGS_SUCCESS',
  FETCH_ALL_RECENT_HAPPENINGS_ERROR: 'FETCH_ALL_RECENT_HAPPENINGS_ERROR',
  FETCH_MY_RECENT_HAPPENINGS: 'FETCH_MY_RECENT_HAPPENINGS',
  FETCH_MY_RECENT_HAPPENINGS_SUCCESS: 'FETCH_MY_RECENT_HAPPENINGS_SUCCESS',
  FETCH_MY_RECENT_HAPPENINGS_ERROR: 'FETCH_MY_RECENT_HAPPENINGS_ERROR',
  FETCH_RECENT_HAPPENING_TYPES: 'FETCH_RECENT_HAPPENING_TYPES',
  FETCH_RECENT_HAPPENING_TYPES_SUCCESS: 'FETCH_RECENT_HAPPENING_TYPES_SUCCESS',
  FETCH_RECENT_HAPPENING_TYPES_ERROR: 'FETCH_RECENT_HAPPENING_TYPES_ERROR',
  CREATE_RECENT_HAPPENING: 'CREATE_RECENT_HAPPENING',
  CREATE_RECENT_HAPPENING_SUCCESS: 'CREATE_RECENT_HAPPENING_SUCCESS',
  CREATE_RECENT_HAPPENING_ERROR: 'CREATE_RECENT_HAPPENING_ERROR',
  UPDATE_RECENT_HAPPENING: 'UPDATE_RECENT_HAPPENING',
  UPDATE_RECENT_HAPPENING_SUCCESS: 'UPDATE_RECENT_HAPPENING_SUCCESS',
  UPDATE_RECENT_HAPPENING_ERROR: 'UPDATE_RECENT_HAPPENING_ERROR'
};
