module.exports = {
  ADD_VIDEO: 'ADD_VIDEO',
  ADD_VIDEO_SUCCESS: 'ADD_VIDEO_SUCCESS',
  ADD_VIDEO_ERROR: 'ADD_VIDEO_ERROR',
  UPDATE_VIDEO: 'UPDATE_VIDEO',
  UPDATE_VIDEO_SUCCESS: 'UPDATE_VIDEO_SUCCESS',
  UPDATE_VIDEO_ERROR: 'UPDATE_VIDEO_ERROR'
};
